# Pandas

#### Seri Oluşturma

In [5]:
import pandas as pd
seri = pd.Series([1,2,3,4,5])
print(seri)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
type(seri)

pandas.Series

In [ ]:
seri.axes #serinin indexlerini döndürür

[RangeIndex(start=0, stop=5, step=1)]

In [8]:
seri.dtype

dtype('int64')

In [9]:
seri.size

5

In [10]:
seri.ndim

1

In [11]:
seri.values

array([1, 2, 3, 4, 5])

In [14]:
seri.head(2)

0    1
1    2
dtype: int64

In [15]:
seri.tail(4)

1    2
2    3
3    4
4    5
dtype: int64

In [17]:
seri = pd.Series([99,22,61,23,16,4856], index = [1,3,2,61,821,45234])
print(seri)

1          99
3          22
2          61
61         23
821        16
45234    4856
dtype: int64

In [22]:
seri = pd.Series([99,22,61,23,4856], index = ["a","b","c","d","e"])
print(seri)

a      99
b      22
c      61
d      23
e    4856
dtype: int64

In [23]:
seri["a"]

np.int64(99)

In [24]:
seri["a":"c"]

a    99
b    22
c    61
dtype: int64

In [27]:
dict = {"reg": 10, "log":11, "cart":12}
seri = pd.Series(dict)
print(seri)

reg     10
log     11
cart    12
dtype: int64

In [28]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

#### Eleman İşlemleri

In [30]:
import pandas as pd
import numpy as np

a = np.array([1,2,33,444,75])
seri = pd.Series(a)
print(seri)

0      1
1      2
2     33
3    444
4     75
dtype: int64

In [32]:
print(seri[0])
print(seri[0:3])

1
0     1
1     2
2    33
dtype: int64

In [33]:
seri = pd.Series([121,200,150,99], index = ["reg","loj","cart","rf"])
print(seri)

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [35]:
print(seri.index)
print(seri.axes)

Index(['reg', 'loj', 'cart', 'rf'], dtype='str')
[Index(['reg', 'loj', 'cart', 'rf'], dtype='str')]

In [36]:
print(seri.keys)

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [39]:
print(list(seri.items()))

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [40]:
print(seri.values)

[121 200 150  99]

In [43]:
"reg" in seri #mevcudiyeti sorgulama

True

In [44]:
print(seri["reg"])

121

In [46]:
print(seri[["rf","reg"]])

rf      99
reg    121
dtype: int64

In [48]:
seri["reg"] = 130
print(seri)

reg     130
loj     200
cart    150
rf       99
dtype: int64

In [50]:
print(seri["reg":"loj"])

reg    130
loj    200
dtype: int64

#### Dataframe Oluşturma

In [51]:
import pandas as pd

In [52]:
l = [1,2,39,67,90]
pd.DataFrame(l, columns = ["degisken_ismi"])

   degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [53]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
df = pd.DataFrame(m, columns = ["var1", "var2", "var3"])
df.head()

   var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [59]:
print(df.columns)
df.columns = ("deg1", "deg2", "deg3")
print(df.columns)

Index(['var1', 'var2', 'var3'], dtype='str')
Index(['deg1', 'deg2', 'deg3'], dtype='str')

In [60]:
type(df)

pandas.DataFrame

In [61]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='str')]

In [62]:
df.ndim

2

In [63]:
df.size

9

In [64]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
type(df.values)

numpy.ndarray

In [66]:
df.head()

   deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [68]:
df.tail()

   deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [70]:
a = np.array([1,2,3,4,5])
df = pd.DataFrame(a, columns = ["deg"])
print(df)

   deg
0    1
1    2
2    3
3    4
4    5

#### Eleman İşlemleri

In [74]:
import numpy as np
s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
s3 = np.random.randint(10, size=5)
dict = {"var1":s1,"var2":s2,"var3":s3}
dict

{'var1': array([3, 7, 7, 8, 1], dtype=int32),
 'var2': array([8, 2, 2, 1, 4], dtype=int32),
 'var3': array([5, 1, 3, 3, 7], dtype=int32)}

In [ ]:
import pandas as pd
df = pd.DataFrame(dict)
print(df)
print(df.index)
df.index = ["a","b","c","d","e"]
print(df)

   var1  var2  var3
0     3     8     5
1     7     2     1
2     7     2     3
3     8     1     3
4     1     4     7
RangeIndex(start=0, stop=5, step=1)
   var1  var2  var3
a     3     8     5
b     7     2     1
c     7     2     3
d     8     1     3
e     1     4     7

In [108]:
dfg = df.drop("a", axis=0)
print(dfg)
print(df)

   var1  var2  var3
b     7     2     1
c     7     2     3
d     8     1     3
e     1     4     7
   var1  var2  var3
a     3     8     5
b     7     2     1
c     7     2     3
d     8     1     3
e     1     4     7

In [104]:
df.drop("a", axis=0, inplace = True)
print(df)

   var1  var2  var3
b     7     2     1
c     7     2     3
d     8     1     3
e     1     4     7