# Pandas

#### Seri Oluşturma

In [2]:
import pandas as pd
seri = pd.Series([1,2,3,4,5])
print(seri)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
type(seri)

pandas.Series

In [4]:
seri.axes #serinin indexlerini döndürür

[RangeIndex(start=0, stop=5, step=1)]

In [5]:
seri.dtype

dtype('int64')

In [6]:
seri.size

5

In [7]:
seri.ndim

1

In [8]:
seri.values

array([1, 2, 3, 4, 5])

In [9]:
seri.head(2)

0    1
1    2
dtype: int64

In [10]:
seri.tail(4)

1    2
2    3
3    4
4    5
dtype: int64

In [11]:
seri = pd.Series([99,22,61,23,16,4856], index = [1,3,2,61,821,45234])
print(seri)

1          99
3          22
2          61
61         23
821        16
45234    4856
dtype: int64

In [12]:
seri = pd.Series([99,22,61,23,4856], index = ["a","b","c","d","e"])
print(seri)

a      99
b      22
c      61
d      23
e    4856
dtype: int64

In [13]:
seri["a"]

np.int64(99)

In [14]:
seri["a":"c"]

a    99
b    22
c    61
dtype: int64

In [15]:
dict = {"reg": 10, "log":11, "cart":12}
seri = pd.Series(dict)
print(seri)

reg     10
log     11
cart    12
dtype: int64

In [16]:
pd.concat([seri,seri])

reg     10
log     11
cart    12
reg     10
log     11
cart    12
dtype: int64

#### Eleman İşlemleri

In [17]:
import pandas as pd
import numpy as np

a = np.array([1,2,33,444,75])
seri = pd.Series(a)
print(seri)

0      1
1      2
2     33
3    444
4     75
dtype: int64

In [18]:
print(seri[0])
print(seri[0:3])

1
0     1
1     2
2    33
dtype: int64

In [19]:
seri = pd.Series([121,200,150,99], index = ["reg","loj","cart","rf"])
print(seri)

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [20]:
print(seri.index)
print(seri.axes)

Index(['reg', 'loj', 'cart', 'rf'], dtype='str')
[Index(['reg', 'loj', 'cart', 'rf'], dtype='str')]

In [21]:
print(seri.keys)

<bound method Series.keys of reg     121
loj     200
cart    150
rf       99
dtype: int64>

In [22]:
print(list(seri.items()))

[('reg', 121), ('loj', 200), ('cart', 150), ('rf', 99)]

In [23]:
print(seri.values)

[121 200 150  99]

In [24]:
"reg" in seri #mevcudiyeti sorgulama

True

In [25]:
print(seri["reg"])

121

In [26]:
print(seri[["rf","reg"]])

rf      99
reg    121
dtype: int64

In [27]:
seri["reg"] = 130
print(seri)

reg     130
loj     200
cart    150
rf       99
dtype: int64

In [28]:
print(seri["reg":"loj"])

reg    130
loj    200
dtype: int64

#### Dataframe Oluşturma

In [29]:
import pandas as pd

In [30]:
l = [1,2,39,67,90]
pd.DataFrame(l, columns = ["degisken_ismi"])

   degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [31]:
import numpy as np
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
df = pd.DataFrame(m, columns = ["var1", "var2", "var3"])
df.head()

   var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [33]:
print(df.columns)
df.columns = ("deg1", "deg2", "deg3")
print(df.columns)

Index(['var1', 'var2', 'var3'], dtype='str')
Index(['deg1', 'deg2', 'deg3'], dtype='str')

In [34]:
type(df)

pandas.DataFrame

In [35]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='str')]

In [36]:
df.ndim

2

In [37]:
df.size

9

In [38]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
type(df.values)

numpy.ndarray

In [40]:
df.head()

   deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [41]:
df.tail()

   deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [42]:
a = np.array([1,2,3,4,5])
df = pd.DataFrame(a, columns = ["deg"])
print(df)

   deg
0    1
1    2
2    3
3    4
4    5

#### Eleman İşlemleri

In [43]:
import numpy as np
s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
s3 = np.random.randint(10, size=5)
dict = {"var1":s1,"var2":s2,"var3":s3}
dict

{'var1': array([6, 7, 4, 2, 4], dtype=int32),
 'var2': array([2, 5, 8, 4, 6], dtype=int32),
 'var3': array([4, 3, 9, 7, 3], dtype=int32)}

In [44]:
import pandas as pd
df = pd.DataFrame(dict)
print(df)
print(df.index)
df.index = ["a","b","c","d","e"]
print(df)

   var1  var2  var3
0     6     2     4
1     7     5     3
2     4     8     9
3     2     4     7
4     4     6     3
RangeIndex(start=0, stop=5, step=1)
   var1  var2  var3
a     6     2     4
b     7     5     3
c     4     8     9
d     2     4     7
e     4     6     3

In [45]:
dfg = df.drop("a", axis=0)
print(dfg)
print(df)

   var1  var2  var3
b     7     5     3
c     4     8     9
d     2     4     7
e     4     6     3
   var1  var2  var3
a     6     2     4
b     7     5     3
c     4     8     9
d     2     4     7
e     4     6     3

In [46]:
df.drop("a", axis=0, inplace = True) #kalıcı silme
print(df)

   var1  var2  var3
b     7     5     3
c     4     8     9
d     2     4     7
e     4     6     3

In [47]:
l = {"d","c"} #fancy in pandas
df = df.drop(l, axis=0)
print(df)

   var1  var2  var3
b     7     5     3
e     4     6     3

In [ ]:
print("var1" in df, "\n")
l = {"var1", "var2", "var4"}
for i in l:
    print(i in df)

True

True
False
True

Index(['var1', 'var2', 'var3'], dtype='str')

In [49]:
print(df["var1"])
df["var4"]=df["var1"]/df["var2"]
print(df)

b    7
e    4
Name: var1, dtype: int32
   var1  var2  var3      var4
b     7     5     3  1.400000
e     4     6     3  0.666667

In [50]:
df = df.drop("var4", axis=1)
print(df)

   var1  var2  var3
b     7     5     3
e     4     6     3

#### Gözlem ve Değişken Seçimi(loc, iloc)

In [51]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
print(df, "\n")
print(df[:1], "\n")
print(df["var1"]) #sütunu verir

   var1  var2  var3
0    10    26     8
1    25     4     4
2    23    14    27
3    29     9     8
4    10    26    15
5     4    16     1
6    13    17    21
7     6     3    22
8     7    18    28
9    23    20     1

   var1  var2  var3
0    10    26     8

0    10
1    25
2    23
3    29
4    10
5     4
6    13
7     6
8     7
9    23
Name: var1, dtype: int32

In [52]:
print(df.loc[0:3])
print(df.iloc[0:3])

   var1  var2  var3
0    10    26     8
1    25     4     4
2    23    14    27
3    29     9     8
   var1  var2  var3
0    10    26     8
1    25     4     4
2    23    14    27

In [53]:
print(df.loc[0:3, "var3"])
print(df.iloc[0:4, 2])

0     8
1     4
2    27
3     8
Name: var3, dtype: int32
0     8
1     4
2    27
3     8
Name: var3, dtype: int32

In [54]:
print(df, "\n")
print(df.iloc[0], "\n") #satırı verir
print(df["var1"], "\n") #var1'in hepsini verir
print(df["var1"][1], "\n") #var1'in 2. satırdaki değerini verir
print(df[0:2][["var1","var2"]]) #ilk iki satırdaki var1 ve var2 değerlerini verir

   var1  var2  var3
0    10    26     8
1    25     4     4
2    23    14    27
3    29     9     8
4    10    26    15
5     4    16     1
6    13    17    21
7     6     3    22
8     7    18    28
9    23    20     1

var1    10
var2    26
var3     8
Name: 0, dtype: int32

0    10
1    25
2    23
3    29
4    10
5     4
6    13
7     6
8     7
9    23
Name: var1, dtype: int32

25

   var1  var2
0    10    26
1    25     4

#### Koşullu Eleman İşlemleri

In [55]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (10,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
print(df, "\n")

   var1  var2  var3
0     4    20    23
1    12    16    25
2     1     1    23
3     4     6     1
4    16     3    20
5     9    28    19
6     8    26    22
7    18    29    10
8    14    14    22
9    21     6    24

In [56]:
print(df.var1, "\n") #Başka bir sütun çağırma işlemi
print(df[df.var1 > 20])

0     4
1    12
2     1
3     4
4    16
5     9
6     8
7    18
8    14
9    21
Name: var1, dtype: int32

   var1  var2  var3
9    21     6    24

In [57]:
print(df[(df.var1 > 20) & (df.var3 < 5)])

Empty DataFrame
Columns: [var1, var2, var3]
Index: []

In [68]:
print(df.loc[(df.var1 > 15), ["var1", "var2"]]) #var1'in 15'ten büyük olduğu durumlarda var1 ve var2'i getir

   var1  var2
1    21    23
3    18    24
4    23    27

#### Dataframe Birleştirme (Concat)

In [59]:
import numpy as np
import pandas as pd
m = np.random.randint(1,30, size = (5,3))
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
print(df, "\n")

   var1  var2  var3
0     4     8    15
1    21    23     5
2     6     1    19
3    18    24     3
4    23    27    28

In [60]:
df2 = df*5
df2

   var1  var2  var3
0    20    40    75
1   105   115    25
2    30     5    95
3    90   120    15
4   115   135   140

In [61]:
pd.concat([df, df2], ignore_index = True, axis = 0)

   var1  var2  var3
0     4     8    15
1    21    23     5
2     6     1    19
3    18    24     3
4    23    27    28
5    20    40    75
6   105   115    25
7    30     5    95
8    90   120    15
9   115   135   140

In [62]:
df2.columns = ["var1", "var2", "zorti"]

In [63]:
pd.concat([df, df2], ignore_index = True, axis = 0, join = "inner") #ortakları al

   var1  var2
0     4     8
1    21    23
2     6     1
3    18    24
4    23    27
5    20    40
6   105   115
7    30     5
8    90   120
9   115   135

In [64]:
pd.concat([df, df2], ignore_index = True, axis = 0, join = "outer") #ikisinden gelen sütunlarıda al

   var1  var2  var3  zorti
0     4     8  15.0    NaN
1    21    23   5.0    NaN
2     6     1  19.0    NaN
3    18    24   3.0    NaN
4    23    27  28.0    NaN
5    20    40   NaN   75.0
6   105   115   NaN   25.0
7    30     5   NaN   95.0
8    90   120   NaN   15.0
9   115   135   NaN  140.0

In [65]:
pd.concat([df, df2], ignore_index = True, axis = 0).reindex(columns=df2.columns) #df2'nin sütunlarına göre biçimlendir

   var1  var2  zorti
0     4     8    NaN
1    21    23    NaN
2     6     1    NaN
3    18    24    NaN
4    23    27    NaN
5    20    40   75.0
6   105   115   25.0
7    30     5   95.0
8    90   120   15.0
9   115   135  140.0

#### İleri Birleştirme İşlemleri (Merge)

In [69]:
df1 = pd.DataFrame({'calisanlar': ['Ali', 'Veli', 'Ayse', 'Fatma'],'grup': ['Muhasebe', 'Muhendislik', 'Muhendislik', 'İK']})

df1

  calisanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [70]:
df2 = pd.DataFrame({'calisanlar': ['Ayse', 'Ali', 'Veli', 'Fatma'],'ilk_giris': [2010, 2009, 2014, 2019]})

df2

  calisanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [ ]:
pd.merge(df1, df2) #ortak column'u kendi otomatik anlar ve onun üzerinden birleştirir

  calisanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [79]:
df3 = pd.merge(df1, df2, on = "calisanlar") #calisanlar column'u üzerinden birleştir

In [76]:
df4 = pd.DataFrame({'grup': ['Muhasebe', 'Muhendislik', 'İK'],'mudur': ['Caner', 'Mustafa', 'Berkcan']})
df4

          grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [81]:
pd.merge(df3, df4) #many to one merge

  calisanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [82]:
df5 = pd.DataFrame({'grup': ['Muhasebe', 'Muhasebe',
                              'Muhendislik', 'Muhendislik', 'İK', 'İK'],
                    'yetenekler': ['matematik', 'excel', 'kodlama', 'linux',
                               'excel', 'yonetim']})

df5

          grup yetenekler
0     Muhasebe  matematik
1     Muhasebe      excel
2  Muhendislik    kodlama
3  Muhendislik      linux
4           İK      excel
5           İK    yonetim

In [84]:
pd.merge(df1, df5) #many to many merge

  calisanlar         grup yetenekler
0        Ali     Muhasebe  matematik
1        Ali     Muhasebe      excel
2       Veli  Muhendislik    kodlama
3       Veli  Muhendislik      linux
4       Ayse  Muhendislik    kodlama
5       Ayse  Muhendislik      linux
6      Fatma           İK      excel
7      Fatma           İK    yonetim

#### Aggregation and Grouping

In [91]:
import seaborn as sns
import pandas as pd
df = sns.load_dataset("planets")
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [99]:
print(df.shape)
print(df.ndim)
print(df["mass"].mean())
print(df["mass"].var())
print(df["mass"].count())
print(df["mass"].sum())
print(df["mass"].median())
print(df["mass"].min())

(1035, 6)
2
2.6381605847953216
14.58183312700122
513
1353.37638
1.26
0.0036

In [102]:
print(df.describe().T)

                 count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254
mass             513.0     2.638161      3.818617     0.003600     0.22900
distance         808.0   264.069282    733.116493     1.350000    32.56000
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000

                      50%       75%       max
number             1.0000     2.000       7.0
orbital_period    39.9795   526.005  730000.0
mass               1.2600     3.040      25.0
distance          55.2500   178.500    8500.0
year            2010.0000  2012.000    2014.0

In [ ]:
print(df.dropna().describe().T) #null olan değerleri atıp describe etme

                count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225
mass            498.0     2.509320     3.636274     0.0036     0.21250
distance        498.0    52.068213    46.596041     1.3500    24.49750
year            498.0  2007.377510     4.167284  1989.0000  2005.00000

                     50%        75%      max
number             1.000     2.0000      6.0
orbital_period   357.000   999.6000  17337.5
mass               1.245     2.8675     25.0
distance          39.940    59.3325    354.0
year            2009.000  2011.0000   2014.0

#### Grouping

In [104]:
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],'veri': [10,11,52,23,43,55]}, columns=['gruplar', 'veri'])
df

  gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [107]:
print(df.groupby("gruplar").mean())
print(df.groupby("gruplar").sum())

         veri
gruplar
A        16.5
B        27.0
C        53.5
         veri
gruplar
A          33
B          54
C         107

In [ ]:
df = sns.load_dataset("planets")
print(df.head())

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009
                                 number  orbital_period      mass  \
method
Astrometry                     1.000000      631.180000       NaN
Eclipse Timing Variations      1.666667     4751.644444  5.125000
Imaging                        1.315789   118247.737500       NaN
Microlensing                   1.173913     3153.571429       NaN
Orbital Brightness Modulation  1.666667        0.709307       NaN
Pulsar Timing                  2.200000     7343.021201       NaN
Pulsation Timing Variations    1.000000     1170.000000       NaN
Radial Velocity                1.721519      823.354680  2.630699
Transit                        1.954660       21.102073  1.470000
Transit Timing Variations      2.250000       79.783500       NaN

                                  distance         year
method
Astrometry                       17.875000  2011.500000
Eclipse Timing Variations       315.360000  2010.000000
Imaging                          67.715937  2009.131579
Microlensing                   4144.000000  2009.782609
Orbital Brightness Modulation  1180.000000  2011.666667
Pulsar Timing                  1200.000000  1998.400000
Pulsation Timing Variations            NaN  2007.000000
Radial Velocity                  51.600208  2007.518987
Transit                         599.298080  2011.236776
Transit Timing Variations      1104.333333  2012.500000
method
Astrometry                            NaN
Eclipse Timing Variations        5.125000
Imaging                               NaN
Microlensing                          NaN
Orbital Brightness Modulation         NaN
Pulsar Timing                         NaN
Pulsation Timing Variations           NaN
Radial Velocity                  2.630699
Transit                          1.470000
Transit Timing Variations             NaN
Name: mass, dtype: float64
                               number  orbital_period  mass  distance  year
method
Astrometry                          2               2     0         2     2
Eclipse Timing Variations           9               9     2         4     9
Imaging                            38              12     0        32    38
Microlensing                       23               7     0        10    23
Orbital Brightness Modulation       3               3     0         2     3
Pulsar Timing                       5               5     0         1     5
Pulsation Timing Variations         1               1     0         0     1
Radial Velocity                   553             553   510       530   553
Transit                           397             397     1       224   397
Transit Timing Variations           4               3     0         3     4

In [118]:
print(df.groupby("method").mean())
print(df.groupby("method").count())

                                 number  orbital_period      mass  \
method
Astrometry                     1.000000      631.180000       NaN
Eclipse Timing Variations      1.666667     4751.644444  5.125000
Imaging                        1.315789   118247.737500       NaN
Microlensing                   1.173913     3153.571429       NaN
Orbital Brightness Modulation  1.666667        0.709307       NaN
Pulsar Timing                  2.200000     7343.021201       NaN
Pulsation Timing Variations    1.000000     1170.000000       NaN
Radial Velocity                1.721519      823.354680  2.630699
Transit                        1.954660       21.102073  1.470000
Transit Timing Variations      2.250000       79.783500       NaN

                                  distance         year
method
Astrometry                       17.875000  2011.500000
Eclipse Timing Variations       315.360000  2010.000000
Imaging                          67.715937  2009.131579
Microlensing                   4144.000000  2009.782609
Orbital Brightness Modulation  1180.000000  2011.666667
Pulsar Timing                  1200.000000  1998.400000
Pulsation Timing Variations            NaN  2007.000000
Radial Velocity                  51.600208  2007.518987
Transit                         599.298080  2011.236776
Transit Timing Variations      1104.333333  2012.500000
                               number  orbital_period  mass  distance  year
method
Astrometry                          2               2     0         2     2
Eclipse Timing Variations           9               9     2         4     9
Imaging                            38              12     0        32    38
Microlensing                       23               7     0        10    23
Orbital Brightness Modulation       3               3     0         2     3
Pulsar Timing                       5               5     0         1     5
Pulsation Timing Variations         1               1     0         0     1
Radial Velocity                   553             553   510       530   553
Transit                           397             397     1       224   397
Transit Timing Variations           4               3     0         3     4

In [ ]:
print(df.groupby("method")["orbital_period"].mean()) #yukardaki sorgunun alınıp sadece orbital_period'a uygulanmış hali

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [122]:
print(df.groupby("method")["orbital_period"].describe().T)

method   Astrometry  Eclipse Timing Variations        Imaging  Microlensing  \
count      2.000000                   9.000000      12.000000      7.000000
mean     631.180000                4751.644444  118247.737500   3153.571429
std      544.217663                2499.130945  213978.177277   1113.166333
min      246.360000                1916.250000    4639.150000   1825.000000
25%      438.770000                2900.000000    8343.900000   2375.000000
50%      631.180000                4343.500000   27500.000000   3300.000000
75%      823.590000                5767.000000   94250.000000   3550.000000
max     1016.000000               10220.000000  730000.000000   5100.000000

method  Orbital Brightness Modulation  Pulsar Timing  \
count                        3.000000       5.000000
mean                         0.709307    7343.021201
std                          0.725493   16313.265573
min                          0.240104       0.090706
25%                          0.291496      25.262000
50%                          0.342887      66.541900
75%                          0.943908      98.211400
max                          1.544929   36525.000000

method  Pulsation Timing Variations  Radial Velocity     Transit  \
count                           1.0        553.00000  397.000000
mean                         1170.0        823.35468   21.102073
std                             NaN       1454.92621   46.185893
min                          1170.0          0.73654    0.355000
25%                          1170.0         38.02100    3.160630
50%                          1170.0        360.20000    5.714932
75%                          1170.0        982.00000   16.145700
max                          1170.0      17337.50000  331.600590

method  Transit Timing Variations
count                    3.000000
mean                    79.783500
std                     71.599884
min                     22.339500
25%                     39.675250
50%                     57.011000
75%                    108.505500
max                    160.000000

#### Aggregate

In [123]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

  gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [ ]:
print(df.groupby("gruplar").aggregate(["min", "median", "max"])) #istediğim istatistikleri getir

        degisken1            degisken2
              min median max       min median  max
gruplar
A              10   16.0  22       100  181.0  262
B              11   17.0  23       111  182.0  253
C              33   66.0  99       333  651.0  969

In [ ]:
print(df.groupby("gruplar").aggregate({"degisken1":"min", "degisken2":"count"})) #farklı columnlardan farklı istediğimiz şeyleri getirme

         degisken1  degisken2
gruplar
A               10          2
B               11          2
C               33          2

#### Filter(Koşula göre veri seçer)

In [131]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

  gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [134]:
def filter_func(x):
    return x["degisken1"].mean() > 20

In [133]:
df.groupby("gruplar").mean()

         degisken1  degisken2
gruplar
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [ ]:
df.groupby("gruplar").filter(filter_func) #A, B, C  olarak gruplandıktan sonra degisken1 mean değeri 20'den büyük olan elemanları yazdırır

  gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

In [ ]:
'''
df.groupby("gruplar").filter(
    lambda x: x["degisken1"].mean() > 20
)
''' 
#lambda x ile kısa bir fonksiyon gibi de tanımlayabiliriz, aynı işi yapar yani

#### Transform(Verilerin boyutunu koruyarak dönüşüm yapar)

In [137]:
import pandas as pd
df = pd.DataFrame({'gruplar': ['A', 'B', 'C', 'A', 'B', 'C'],
                   'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['gruplar', 'degisken1', 'degisken2'])
df

  gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [141]:
df_a = df.iloc[:,1:4]
df_a

   degisken1  degisken2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

In [ ]:
df_a.transform(lambda x: (x-x.mean())/x.std()) #x fonksiyona sırayla gönderdiğimiz her bir sütunu temsil eder.
'''
Pandas bunu her satıra ayrı ayrı fonksiyon çağırarak değil, 
sütunun tamamına tek seferde vektörel işlem uygulayarak gerçekleştiriyor.
'''

   degisken1  degisken2
0  -0.687871  -0.738461
1  -0.299074  -0.263736
2   0.000000  -0.015514
3  -0.328982  -0.235811
4  -0.657963  -0.704331
5   1.973890   1.957853

#### Apply(Bir fonksiyonu satırlara veya sütunlara uygular)

In [156]:
import pandas as pd
df = pd.DataFrame({'degisken1': [10,23,33,22,11,99],
                   'degisken2': [100,253,333,262,111,969]},
                   columns = ['degisken1', 'degisken2'])
df

   degisken1  degisken2
0         10        100
1         23        253
2         33        333
3         22        262
4         11        111
5         99        969

In [157]:
df.apply(np.sum)

degisken1     198
degisken2    2028
dtype: int64

In [ ]:
df.apply(lambda x: x.mean(), axis=1) #her satıra mean uygular

0     55.0
1    138.0
2    183.0
3    142.0
4     61.0
5    534.0
dtype: float64

In [161]:
df = pd.DataFrame({
    "vize": [60, 80, 40],
    "final": [70, 90, 50]
})

df["ortalama"] = df.apply(
    lambda x: x["vize"] * 0.4 + x["final"] * 0.6,
    axis=1
)
print(df)

   vize  final  ortalama
0    60     70      66.0
1    80     90      86.0
2    40     50      46.0

#### Pivot Tablolar

In [2]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [167]:
titanic.groupby("sex")["survived"].mean()

sex
female    0.742038
male      0.188908
Name: survived, dtype: float64

In [176]:
titanic.groupby(["sex","class"])["survived"].aggregate("mean").unstack()

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [3]:
titanic.pivot_table(values = "survived", index="sex", columns="class")

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [5]:
age = pd.cut(titanic["age"], [0,18,90])
age.head(10)

0    (18.0, 90.0]
1    (18.0, 90.0]
2    (18.0, 90.0]
3    (18.0, 90.0]
4    (18.0, 90.0]
5             NaN
6    (18.0, 90.0]
7     (0.0, 18.0]
8    (18.0, 90.0]
9     (0.0, 18.0]
Name: age, dtype: category
Categories (2, interval[int64, right]): [(0, 18] < (18, 90]]

In [6]:
titanic.pivot_table(values = "survived", index=["sex", age], columns="class")

class               First    Second     Third
sex    age
female (0, 18]   0.909091  1.000000  0.511628
       (18, 90]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 90]  0.375000  0.071429  0.133663

#### Dış Kaynaklı Veri Okuma

In [191]:
pd.read_csv("reading_data/ornekcsv.csv", sep=";") #; ile ayrılmış

      a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0

In [194]:
pd.read_csv("reading_data/duz_metin.txt")

    1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2
6   8 2
7   9 2
8  10 2

In [199]:
df = pd.read_excel("reading_data/ornekx.xlsx")
df.head()

    a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0

In [202]:
import seaborn as sab
tips = sab.load_dataset("tips")
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4